# -*- coding: utf-8 -*-
"""download_youtube.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BNwMETNGiTOnZtfqIRI5h61dY182ci8K
"""

from pytube import YouTube
from pydub import AudioSegment
import os

def download_youtube_video_to_mp3(video_url):
    try:
        # Create YouTube object
        yt = YouTube(video_url)

        # Get the highest resolution stream
        video_stream = yt.streams.filter(only_audio=True).first()

        if not video_stream:
            return "No audio streams available."

        # Download the video
        video_file = video_stream.download(filename='temp_video')

        # Convert video to audio
        audio_file = yt.title + '.mp3'
        audio = AudioSegment.from_file(video_file)
        audio.export(audio_file, format='mp3')

        # Clean up temporary video file
        os.remove(video_file)

        return f'Conversion complete! Saved as: {audio_file}'
    except Exception as e:
        return f'Error: {e}'

